### ISSUE TITLE
What does js-multiaddr do?

### ISSUE THREAD

**Issue by noffle** [jbenet/js-multiaddr#12]
It's not clear from the first textful of README what `js-multiaddr` does. It's an implementation of multiaddr, but what does that mean? The README should ideally aim to very quickly answer the question "what are the inputs and outputs of this module", or "what does this module do"?

**Comment by diasdavid** [comment]
Do you still have this question, @noffle ?

**Comment by noffle** [comment]
I think it's enough for js-multiaddr to state itself as a JS impl of multiaddr, but we could definitely use more doc <3 on [jbenet/multiaddr](https://github.com/jbenet/multiaddr) for brand new users unfamiliar with the big ideas of multiaddr. Let's close this and focus efforts over there.
