### ISSUE TITLE
We are renaming the prefix of our JavaScript modules from 'node-' to 'js-'

### ISSUE THREAD

**Issue by diasdavid** [jbenet/js-multiaddr#3]
https://github.com/ipfs/js-ipfs/issues/32

TODO (@jbenet)
- [x] merge PR
- [x] change github repo name
- [ ] publish to npm

**Comment by jbenet** [comment]
cant republish now. the change is minor and will go out in the future. github redirects old names anyway

**Comment by diasdavid** [comment]
sounds good :)
